CREATE DATABASE IF NOT EXISTS matcha;

USE matcha;

CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL AUTO_INCREMENT,
	userName VARCHAR(25) NOT NULL,
	pswd VARCHAR(255) NOT NULL,
	mail VARCHAR(50) NOT NULL,
	level TINYINT NOT NULL DEFAULT 0,
	profilId INT,
	creationDate TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP()),
	modificationDate TIMESTAMP,
	PRIMARY KEY (id)
);

ALTER TABLE users AUTO_INCREMENT=10000001;

CREATE TABLE IF NOT EXISTS profils (
	id INT NOT NULL AUTO_INCREMENT,
	firstName VARCHAR(25) NOT NULL,
	lastName VARCHAR(25) NOT NULL,
	birthDate VARCHAR(25) NOT NULL,
	score INT NOT NULL DEFAULT 0,
	tagsId INT NOT NULL,
	gender CHAR NOT NULL,
	interests JSON, /* {M: true, F: false, etc} */
	about TEXT,
	height SMALLINT,
	wght SMALLINT,
	hair VARCHAR(2),
	eyes VARCHAR(2),
	tatoo BOOLEAN,
	piercing BOOLEAN,
	job VARCHAR(50),
	title VARCHAR(100),
	gps JSON NOT NULL, /* {latitude: value, longitude: value} */
	addr VARCHAR(255),
	pictures JSON, /* {profil: [name1, name2, name3]}, index 1 as profil */
	PRIMARY KEY (id)
);

ALTER TABLE profils AUTO_INCREMENT=10000001;


CREATE TABLE IF NOT EXISTS tags (
	id INT NOT NULL AUTO_INCREMENT,
	profilId INT NOT NULL,
	tag VARCHAR(50) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (profilId)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE tags AUTO_INCREMENT=10000001;


CREATE TABLE IF NOT EXISTS views (
	id INT NOT NULL AUTO_INCREMENT,
	profilIdViewer INT NOT NULL,
	profilIdViewed INT NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (id),
	FOREIGN KEY (profilIdViewer)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (profilIdViewed)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE views AUTO_INCREMENT=10000001;

CREATE TABLE IF NOT EXISTS likes (
	id INT NOT NULL AUTO_INCREMENT,
	profilIdSender INT NOT NULL,
	profilIdReciever INT NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (id),
	FOREIGN KEY (profilIdSender)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (profilIdReciever)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE likes AUTO_INCREMENT=10000001;

CREATE TABLE IF NOT EXISTS blocked (
	id INT NOT NULL AUTO_INCREMENT,
	profilIdSender INT NOT NULL,
	profilIdReciever INT NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (id),
	FOREIGN KEY (profilIdSender)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (profilIdReciever)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE blocked AUTO_INCREMENT=10000001;

CREATE TABLE IF NOT EXISTS favorites (
	id INT NOT NULL AUTO_INCREMENT,
	profilIdSender INT NOT NULL,
	profilIdReciever INT NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (id),
	FOREIGN KEY (profilIdSender)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (profilIdReciever)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE favorites AUTO_INCREMENT=10000001;

CREATE TABLE IF NOT EXISTS contacts (
	id INT NOT NULL AUTO_INCREMENT,
	profilId1 INT NOT NULL,
	profilId2 INT NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (id),
	FOREIGN KEY (profilId1)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (profilId2)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE contacts AUTO_INCREMENT=10000001;

CREATE TABLE IF NOT EXISTS messages (
	id INT NOT NULL AUTO_INCREMENT,
	profilIdSender INT NOT NULL,
	profilIdReciever INT NOT NULL,
	body TEXT NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (id),
	FOREIGN KEY (profilIdSender)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (profilIdReciever)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE messages AUTO_INCREMENT=10000001;

CREATE TABLE IF NOT EXISTS notifications (
	id INT NOT NULL AUTO_INCREMENT,
	profilId INT NOT NULL,
	eventId INT NOT NULL,
	notificationType VARCHAR(25) NOT NULL,
	level TINYINT NOT NULL DEFAULT 0,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (id),
	FOREIGN KEY (profilId)
		REFERENCES profils (id)
		ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE notifications AUTO_INCREMENT=10000001;